// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// PostHello implements postHello operation.
//
// Receives a hello message and returns it back.
//
// POST /hello
func (UnimplementedHandler) PostHello(ctx context.Context, req *HelloRequest) (r PostHelloRes, _ error) {
	return r, ht.ErrNotImplemented
}
