// Code generated by ogen, DO NOT EDIT.

package api

// Ref: #/components/schemas/Error
type Error struct {
	// Error message.
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *Error) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *Error) SetError(val string) {
	s.Error = val
}

func (*Error) postHelloRes() {}

// Ref: #/components/schemas/HelloRequest
type HelloRequest struct {
	// The hello message to echo.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *HelloRequest) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *HelloRequest) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/HelloResponse
type HelloResponse struct {
	// The echoed hello message.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *HelloResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *HelloResponse) SetMessage(val string) {
	s.Message = val
}

func (*HelloResponse) postHelloRes() {}
